public class VariableAndDataTypes{
    public static void main(String[] args){
        int idade = 25;
        System.out.println("A idade é: " + idade);

        double altura = 1.75;
        System.out.println("A altura é: " + altura);

        boolean isEstudante = true;
        System.out.println("É estudante? " + isEstudante);

        char genero = 'M';
        System.out.println("O genero é: " + genero);

        String nome = "Abiner";
        System.out.println("O nome é: " + nome);

    }
}

/*Aqui esta um exemplo de inicialização das variaveis mais comuns */